CREATE DATABASE school_db;
SHOW DATABASES;

USE school_db;

CREATE TABLE Students (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(25) NOT NULL,
age INT CHECK (age > 0),
city VARCHAR(15) NOT NULL
);

SHOW TABLES;

SELECT * FROM STUDENTS;

TRUNCATE TABLE Students;

DROP TABLE Students;